#!/bin/bash

# check-cli.sh — smoke test the shipped command-line binary.
#
# The unit suites drive remux() in process, which is the right place to assert
# on behaviour but leaves one thing unchecked: whether the executable a user
# actually runs starts, links, finds its libraries, and converts a file. This
# runs it end to end on a fixture generated by qsv2flv-make-fixture, so it needs
# no sample video either.
#
# Three assertions, in the order a first-time user meets them: --help works, a
# missing file is refused with a message and a non-zero exit, and a real
# conversion produces a file that a demuxer can open.
#
# Registered with CTest as CliSmoke, so `ctest --preset NAME` covers everything
# CI covers and there is no assertion that only runs when a workflow decides to
# run it. CMake passes the two binaries as arguments; a human names a preset and
# lets this find them.
#
# Usage:
#   ./check-cli.sh                          the release preset's binaries
#   ./check-cli.sh --preset ci-asan-ubsan   the sanitizer build's
#   ./check-cli.sh <cli> <make-fixture>     what CTest invokes

set -euo pipefail

if [[ $# -eq 2 && "$1" != --* ]]; then
  # Invoked by CTest, which knows exactly where the binaries are. Deliberately
  # no build-env.sh on this path: the environment probe it does is about
  # configuring a build, and this test is about a binary that already exists.
  cli="$1"
  fixture_tool="$2"
else
  script_dir="$(cd "$(dirname "$0")" && pwd)"
  # shellcheck source=build-env.sh
  source "${script_dir}/build-env.sh" || exit 1

  preset="${QSV2FLV_DEFAULT_PRESET}"
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --preset)
        if [[ $# -lt 2 ]]; then
          echo "--preset needs a name; run cmake --list-presets." >&2
          exit 1
        fi
        preset="$2"
        shift 2
        ;;
      --preset=*) preset="${1#--preset=}"; shift ;;
      -h|--help)
        echo "Usage: $0 [--preset NAME] | $0 <cli> <make-fixture>" >&2
        exit 0
        ;;
      *)
        echo "Unknown option: $1" >&2
        exit 1
        ;;
    esac
  done

  build_dir="$(qsv2flv_build_dir "${preset}")"
  cli="${build_dir}/qsv2flv-cli"
  fixture_tool="${build_dir}/qsv2flv-make-fixture"
fi

for binary in "${cli}" "${fixture_tool}"; do
  if [[ ! -x "${binary}" ]]; then
    echo "Not built: ${binary}." >&2
    echo "Run ./build.sh --preset ${preset:-release} first." >&2
    exit 1
  fi
done

work="$(mktemp -d)"
trap 'rm -rf "${work}"' EXIT

echo "1/3 --help"
"${cli}" --help | grep -q '^Usage: qsv2flv-cli'

echo "2/3 missing input is refused"
# Inverted with `if !`, not `|| true`: `set -e` would take the non-zero exit as
# a failure of this script, and the whole assertion is that it is non-zero.
if "${cli}" "${work}/absent.qsv" 2>"${work}/stderr.txt"; then
  echo "Expected a non-zero exit for a missing input." >&2
  exit 1
fi
grep -q 'Cannot open the file' "${work}/stderr.txt"

echo "3/3 a real conversion"
"${fixture_tool}" "${work}/sample.qsv" 2 20 >/dev/null
"${cli}" -o "${work}" "${work}/sample.qsv" >/dev/null
if [[ ! -s "${work}/sample.mp4" ]]; then
  echo "qsv2flv-cli produced no output." >&2
  exit 1
fi

# ffprobe is not a build dependency, so this last check is a bonus rather than
# a requirement: on a machine that has it, confirm the result is a file a
# demuxer will open and not just a non-empty one.
if command -v ffprobe >/dev/null 2>&1; then
  ffprobe -v error -show_entries stream=codec_type -of csv=p=0 \
    "${work}/sample.mp4" | grep -q video
  echo "    ffprobe: output holds a video stream"
fi

echo "check-cli.sh PASS"
